### PR TITLE
Fixed search drawer spacing issue

### PR DESCRIPTION
**Pull request by dijs**
Before:
image

After:
image

### CODE REVIEW

**Comment by markbrocato** [comment]
I think I'm missing something.  This doesn't happen for me locally or in production:

https://react-storefront-boilerplate.moovweb.cloud/

**Comment by dijs** [comment]
@markbrocato Maybe it is just an issue when using the component in isolation or specifically in Storybook.

**Comment by markbrocato** [comment]
This adds excessive margins to the component when running in apps.  You should add the padding in storybook itself.

Before:
image

After:
image

**Comment by dijs** [comment]
Will take care of this in Storybook itself.

**Pull request closed without merging**
