### PR TITLE
Prevent MUI warning about overriding NavTabs.classes.tab prop

### PR DESCRIPTION
**Pull request by kevhender**

### CODE REVIEW

**Comment by dijs** [comment]
You need to update the tests

**Comment by kevhender** [comment]
Sure, but are these snapshot tests really useful at all? Seems like they are more trouble than they are worth, since the snapshots are essentially just blindly updated with each code change. I would think that the snapshots should only be used for very small, targeted components.

**Comment by markbrocato** [comment]
They are somewhat useful as a smoke test, in that they exercise different facets of the rendering logic.  It's less brittle to use `find` to look for specific elements being rendered, but the snapshots are quick, easy, and better than nothing.

**Comment by kevhender** [comment]
Okay, I updated the snapshots and added an additional test to keep that class from being removed.

**Pull request merged**
