### PR TITLE
Optimize Images Refactor

### PR DESCRIPTION
**Pull request by dijs**
https://moovweb.atlassian.net/browse/PC-375
https://moovweb.atlassian.net/browse/PC-374

### CODE REVIEW

**Comment by dijs** [comment]
@markbrocato I am thinking of changing the name of this function to `useOptimizer`. Ideas?

**Comment by markbrocato** [comment]
@dijs I'd like to move this into extensions.  See https://github.com/moovweb/react-storefront-extensions/pull/52

**Comment by dijs** [comment]
@markbrocato It looks like you already did move it, should I delete the optimizeImages portion of this PR?

**Comment by markbrocato** [comment]
Closing this as these changes were moved to react-storefront-extensions.

**Pull request closed without merging**
